apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  namespace: <namespace>
data:
  key1: value1
  key2: value2
  app-config.txt: |
    DATABASE_URL=mysql://db.example.com:3306
    API_KEY=abcdef12345
